"""
Factores de emisión iniciales para el MVP.

Estructura:
  - category: identificador interno usado por el backend/LLM
  - main_category: agrupación visible en dashboard
  - display_name: nombre legible para UI
  - unit: unidad esperada para el cálculo
  - factor_kg_co2e: kg CO2e por unidad
  - source_name/source_year/source_type/source_detail/source_url: trazabilidad de fuente
  - notes: observaciones y limitaciones

source_type:
  - official: fuente institucional u organismo oficial
  - scientific_literature: literatura científica, informes técnicos o LCA publicados
  - estimated: estimación propia para completar el MVP

Unidades:
  km       → por kilómetro recorrido
  kg       → por kilogramo consumido / transportado
  kWh      → por kilovatio-hora de electricidad
  hora     → por hora de uso
  unidad   → por pieza / evento / ciclo
  litro    → por litro consumido

Nota TFM:
  Esta base es suficiente para un MVP. No pretende ser una base exhaustiva ni certificada.
  Los factores deben mostrarse como aproximaciones y revisarse si el sistema evoluciona
  a una versión productiva.
"""

EMISSION_FACTORS = [{'category': 'coche_gasolina',
  'main_category': 'Transporte',
  'display_name': 'Coche (gasolina)',
  'unit': 'km',
  'factor_kg_co2e': 0.192,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'passenger car, petrol, average',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'coche_diesel',
  'main_category': 'Transporte',
  'display_name': 'Coche (diésel)',
  'unit': 'km',
  'factor_kg_co2e': 0.171,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'passenger car, diesel, average',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'coche_electrico',
  'main_category': 'Transporte',
  'display_name': 'Coche eléctrico',
  'unit': 'km',
  'factor_kg_co2e': 0.053,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'BEV, mix eléctrico europeo',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'moto',
  'main_category': 'Transporte',
  'display_name': 'Moto / ciclomotor (gasolina)',
  'unit': 'km',
  'factor_kg_co2e': 0.114,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'motorbike, average',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'moto_electrica',
  'main_category': 'Transporte',
  'display_name': 'Moto eléctrica',
  'unit': 'km',
  'factor_kg_co2e': 0.022,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'electric motorbike, mix eléctrico europeo',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'patinete_electrico',
  'main_category': 'Transporte',
  'display_name': 'Patinete eléctrico',
  'unit': 'km',
  'factor_kg_co2e': 0.025,
  'source_name': 'CE Delft',
  'source_year': 2020,
  'source_type': 'scientific_literature',
  'source_detail': 'e-scooter lifecycle',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'taxi',
  'main_category': 'Transporte',
  'display_name': 'Taxi / VTC (Uber)',
  'unit': 'km',
  'factor_kg_co2e': 0.211,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'taxi, average',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'avion_domestico',
  'main_category': 'Transporte',
  'display_name': 'Avión (vuelo doméstico)',
  'unit': 'km',
  'factor_kg_co2e': 0.255,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'domestic flight, economy class',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'avion_internacional',
  'main_category': 'Transporte',
  'display_name': 'Avión (vuelo internacional)',
  'unit': 'km',
  'factor_kg_co2e': 0.195,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'long-haul flight, economy class',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'crucero',
  'main_category': 'Transporte',
  'display_name': 'Crucero (por día)',
  'unit': 'unidad',
  'factor_kg_co2e': 163.0,
  'source_name': 'ICCT',
  'source_year': 2019,
  'source_type': 'official',
  'source_detail': 'cruise ship per passenger day',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'tren',
  'main_category': 'Transporte',
  'display_name': 'Tren (nacional)',
  'unit': 'km',
  'factor_kg_co2e': 0.041,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'national rail average',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'metro',
  'main_category': 'Transporte',
  'display_name': 'Metro / tranvía',
  'unit': 'km',
  'factor_kg_co2e': 0.028,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'light rail / tram',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'autobus',
  'main_category': 'Transporte',
  'display_name': 'Autobús urbano',
  'unit': 'km',
  'factor_kg_co2e': 0.089,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'local bus average',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'autobus_interurbano',
  'main_category': 'Transporte',
  'display_name': 'Autobús interurbano',
  'unit': 'km',
  'factor_kg_co2e': 0.068,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'coach average',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'electricidad_es',
  'main_category': 'Energía',
  'display_name': 'Electricidad (España)',
  'unit': 'kWh',
  'factor_kg_co2e': 0.181,
  'source_name': 'REE',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'factor de emisión mix eléctrico España',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'gas_natural',
  'main_category': 'Energía',
  'display_name': 'Gas natural (hogar)',
  'unit': 'kWh',
  'factor_kg_co2e': 0.203,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'natural gas, combustion',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'calefaccion_gasoil',
  'main_category': 'Energía',
  'display_name': 'Calefacción gasoil',
  'unit': 'litro',
  'factor_kg_co2e': 2.68,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'burning oil',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'aire_acondicionado',
  'main_category': 'Energía',
  'display_name': 'Aire acondicionado',
  'unit': 'hora',
  'factor_kg_co2e': 0.362,
  'source_name': 'REE',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'Estimación: 2 kWh/h × REE 2023 factor España',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'lavadora',
  'main_category': 'Energía',
  'display_name': 'Lavadora (ciclo)',
  'unit': 'unidad',
  'factor_kg_co2e': 0.272,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'washing machine cycle, 1.5 kWh',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'secadora',
  'main_category': 'Energía',
  'display_name': 'Secadora (ciclo)',
  'unit': 'unidad',
  'factor_kg_co2e': 0.724,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'tumble dryer cycle, 4 kWh',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'lavavajillas',
  'main_category': 'Energía',
  'display_name': 'Lavavajillas (ciclo)',
  'unit': 'unidad',
  'factor_kg_co2e': 0.362,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'dishwasher cycle, 2 kWh',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'television',
  'main_category': 'Energía',
  'display_name': 'Televisión',
  'unit': 'hora',
  'factor_kg_co2e': 0.036,
  'source_name': 'REE',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'Estimación: 0.2 kWh/h × REE 2023',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'carne_vacuno',
  'main_category': 'Alimentación',
  'display_name': 'Carne de vacuno',
  'unit': 'kg',
  'factor_kg_co2e': 27.0,
  'source_name': 'IPCC AR6',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'IPCC AR6 / Poore & Nemecek 2018',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'carne_cerdo',
  'main_category': 'Alimentación',
  'display_name': 'Carne de cerdo',
  'unit': 'kg',
  'factor_kg_co2e': 12.1,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Poore & Nemecek 2018',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'carne_pollo',
  'main_category': 'Alimentación',
  'display_name': 'Carne de pollo',
  'unit': 'kg',
  'factor_kg_co2e': 6.9,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Poore & Nemecek 2018',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'carne_procesada',
  'main_category': 'Alimentación',
  'display_name': 'Carne procesada (embutidos, frankfurt)',
  'unit': 'kg',
  'factor_kg_co2e': 11.0,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'processed meat average',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'pescado',
  'main_category': 'Alimentación',
  'display_name': 'Pescado (promedio)',
  'unit': 'kg',
  'factor_kg_co2e': 6.1,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Poore & Nemecek 2018',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'marisco',
  'main_category': 'Alimentación',
  'display_name': 'Marisco / mariscos',
  'unit': 'kg',
  'factor_kg_co2e': 11.4,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'crustaceans average',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'lacteos_leche',
  'main_category': 'Alimentación',
  'display_name': 'Leche / lácteos',
  'unit': 'litro',
  'factor_kg_co2e': 3.2,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Poore & Nemecek 2018',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'queso',
  'main_category': 'Alimentación',
  'display_name': 'Queso',
  'unit': 'kg',
  'factor_kg_co2e': 13.5,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Poore & Nemecek 2018',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'huevos',
  'main_category': 'Alimentación',
  'display_name': 'Huevos',
  'unit': 'unidad',
  'factor_kg_co2e': 0.196,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'eggs per unit (~60g)',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'verduras',
  'main_category': 'Alimentación',
  'display_name': 'Verduras y hortalizas',
  'unit': 'kg',
  'factor_kg_co2e': 2.0,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'vegetables average',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'cereales',
  'main_category': 'Alimentación',
  'display_name': 'Cereales / pan',
  'unit': 'kg',
  'factor_kg_co2e': 1.4,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Poore & Nemecek 2018',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'cafe',
  'main_category': 'Alimentación',
  'display_name': 'Café',
  'unit': 'kg',
  'factor_kg_co2e': 28.5,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'coffee beans',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'chocolate',
  'main_category': 'Alimentación',
  'display_name': 'Chocolate',
  'unit': 'kg',
  'factor_kg_co2e': 46.4,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'dark chocolate',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'alcohol_cerveza',
  'main_category': 'Alimentación',
  'display_name': 'Cerveza',
  'unit': 'litro',
  'factor_kg_co2e': 1.04,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'beer',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'alcohol_vino',
  'main_category': 'Alimentación',
  'display_name': 'Vino',
  'unit': 'litro',
  'factor_kg_co2e': 1.79,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'wine',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'comida_rapida',
  'main_category': 'Alimentación',
  'display_name': 'Comida rápida (hamburguesa/pizza)',
  'unit': 'unidad',
  'factor_kg_co2e': 2.5,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'mixed ingredients',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'aceite_oliva',
  'main_category': 'Alimentación',
  'display_name': 'Aceite de oliva',
  'unit': 'litro',
  'factor_kg_co2e': 6.0,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'olive oil',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'agua_embotellada',
  'main_category': 'Compras',
  'display_name': 'Agua embotellada / botella de agua / botella de agua de plástico',
  'unit': 'litro',
  'factor_kg_co2e': 0.3,
  'source_name': 'Carbon Trust',
  'source_year': 2021,
  'source_type': 'scientific_literature',
  'source_detail': 'bottled water lifecycle (bottle + water + transport)',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'refresco_lata',
  'main_category': 'Alimentación',
  'display_name': 'Refresco en lata',
  'unit': 'unidad',
  'factor_kg_co2e': 0.17,
  'source_name': 'Carbon Trust',
  'source_year': 2021,
  'source_type': 'scientific_literature',
  'source_detail': 'canned soft drink 330ml',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'zumo',
  'main_category': 'Alimentación',
  'display_name': 'Zumo (brick/botella)',
  'unit': 'litro',
  'factor_kg_co2e': 0.55,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'fruit juice average',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'residuo_mixto',
  'main_category': 'Residuos',
  'display_name': 'Residuo mezclado (vertedero)',
  'unit': 'kg',
  'factor_kg_co2e': 0.587,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'landfill waste',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'residuo_reciclado',
  'main_category': 'Residuos',
  'display_name': 'Residuo reciclado',
  'unit': 'kg',
  'factor_kg_co2e': 0.021,
  'source_name': 'DEFRA',
  'source_year': 2023,
  'source_type': 'official',
  'source_detail': 'recycled waste',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'ropa_nueva',
  'main_category': 'Compras',
  'display_name': 'Ropa nueva (prenda)',
  'unit': 'unidad',
  'factor_kg_co2e': 8.0,
  'source_name': 'WRAP Textiles',
  'source_year': 2022,
  'source_type': 'scientific_literature',
  'source_detail': 'average garment',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'zapatillas',
  'main_category': 'Compras',
  'display_name': 'Zapatillas / calzado',
  'unit': 'unidad',
  'factor_kg_co2e': 14.0,
  'source_name': 'MIT Scope 3',
  'source_year': None,
  'source_type': 'scientific_literature',
  'source_detail': 'footwear average',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'libro_nuevo',
  'main_category': 'Compras',
  'display_name': 'Libro nuevo',
  'unit': 'unidad',
  'factor_kg_co2e': 2.71,
  'source_name': 'Book Industry Study Group',
  'source_year': 2008,
  'source_type': 'scientific_literature',
  'source_detail': 'average book',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'smartphone',
  'main_category': 'Compras',
  'display_name': 'Smartphone nuevo',
  'unit': 'unidad',
  'factor_kg_co2e': 70.0,
  'source_name': 'Apple / Samsung LCA reports',
  'source_year': 2023,
  'source_type': 'scientific_literature',
  'source_detail': 'Apple / Samsung LCA reports 2023',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'portatil',
  'main_category': 'Compras',
  'display_name': 'Portátil nuevo',
  'unit': 'unidad',
  'factor_kg_co2e': 400.0,
  'source_name': 'Dell / Apple LCA reports',
  'source_year': 2023,
  'source_type': 'scientific_literature',
  'source_detail': 'Dell / Apple LCA reports 2023',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'streaming',
  'main_category': 'Ocio',
  'display_name': 'Streaming (Netflix/Spotify, por mes)',
  'unit': 'unidad',
  'factor_kg_co2e': 0.036,
  'source_name': 'Carbon Trust',
  'source_year': 2021,
  'source_type': 'scientific_literature',
  'source_detail': 'video streaming per hour × 10h/mes',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'gimnasio',
  'main_category': 'Ocio',
  'display_name': 'Sesión de gimnasio',
  'unit': 'unidad',
  'factor_kg_co2e': 0.502,
  'source_name': 'Estimación propia',
  'source_year': None,
  'source_type': 'estimated',
  'source_detail': 'Estimación: desplazamiento medio 3km coche + instalación',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'hotel',
  'main_category': 'Ocio',
  'display_name': 'Hotel (por noche)',
  'unit': 'unidad',
  'factor_kg_co2e': 22.6,
  'source_name': 'Cornell Hotel Sustainability Benchmarking',
  'source_year': 2022,
  'source_type': 'scientific_literature',
  'source_detail': 'Cornell Hotel Sustainability Benchmarking 2022',
  'source_url': None,
  'notes': 'Factor orientativo para MVP; revisar/actualizar antes de uso productivo.'},
 {'category': 'caminar',
  'main_category': 'Transporte',
  'display_name': 'Caminar',
  'unit': 'km',
  'factor_kg_co2e': 0.0,
  'source_name': 'Estimación propia',
  'source_year': 2026,
  'source_type': 'estimated',
  'source_detail': 'Emisiones directas consideradas cero para el desplazamiento',
  'source_url': None,
  'notes': 'No incluye alimentación adicional ni fabricación de equipamiento.'},
 {'category': 'bicicleta',
  'main_category': 'Transporte',
  'display_name': 'Bicicleta',
  'unit': 'km',
  'factor_kg_co2e': 0.0,
  'source_name': 'Estimación propia',
  'source_year': 2026,
  'source_type': 'estimated',
  'source_detail': 'Emisiones directas consideradas cero para el desplazamiento',
  'source_url': None,
  'notes': 'No incluye ciclo de vida de la bicicleta.'},
 {'category': 'tren_alta_velocidad',
  'main_category': 'Transporte',
  'display_name': 'Tren de alta velocidad',
  'unit': 'km',
  'factor_kg_co2e': 0.015,
  'source_name': 'Estimación propia',
  'source_year': 2026,
  'source_type': 'estimated',
  'source_detail': 'Aproximación para tren eléctrico de larga distancia en España',
  'source_url': None,
  'notes': 'Reemplazar por factor oficial si se incorpora una fuente nacional específica.'},
 {'category': 'legumbres',
  'main_category': 'Alimentación',
  'display_name': 'Legumbres',
  'unit': 'kg',
  'factor_kg_co2e': 0.9,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Pulses average',
  'source_url': None,
  'notes': 'Categoría útil para comparar con proteína animal.'},
 {'category': 'arroz',
  'main_category': 'Alimentación',
  'display_name': 'Arroz',
  'unit': 'kg',
  'factor_kg_co2e': 4.0,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Rice average',
  'source_url': None,
  'notes': 'Factor alto respecto a otros cereales por emisiones de metano en cultivo.'},
 {'category': 'patata',
  'main_category': 'Alimentación',
  'display_name': 'Patata',
  'unit': 'kg',
  'factor_kg_co2e': 0.5,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Potatoes average',
  'source_url': None,
  'notes': 'Factor orientativo.'},
 {'category': 'fruta',
  'main_category': 'Alimentación',
  'display_name': 'Fruta',
  'unit': 'kg',
  'factor_kg_co2e': 1.1,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Fruit average',
  'source_url': None,
  'notes': 'No diferencia fruta local/importada ni transporte aéreo.'},
 {'category': 'tofu_soja',
  'main_category': 'Alimentación',
  'display_name': 'Tofu / soja',
  'unit': 'kg',
  'factor_kg_co2e': 3.0,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Soy products / tofu approximation',
  'source_url': None,
  'notes': 'Categoría útil como alternativa proteica a carne.'},
 {'category': 'tender_ropa',
  'main_category': 'Energía',
  'display_name': 'Tender ropa',
  'unit': 'unidad',
  'factor_kg_co2e': 0.0,
  'source_name': 'Estimación propia',
  'source_year': 2026,
  'source_type': 'estimated',
  'source_detail': 'Alternativa sin consumo eléctrico directo frente a secadora',
  'source_url': None,
  'notes': 'Usado como alternativa para recomendaciones.'},
 {'category': 'agua_grifo',
  'main_category': 'Compras',
  'display_name': 'Agua del grifo',
  'unit': 'litro',
  'factor_kg_co2e': 0.001,
  'source_name': 'Estimación propia',
  'source_year': 2026,
  'source_type': 'estimated',
  'source_detail': 'Aproximación para comparación con agua embotellada',
  'source_url': None,
  'notes': 'Factor muy orientativo; depende del tratamiento y distribución local.'},

 # ─── CARNES ESPECÍFICAS ────────────────────────────────────────────────────
 {'category': 'carne_cordero',
  'main_category': 'Alimentación',
  'display_name': 'Carne de cordero / ovino',
  'unit': 'kg',
  'factor_kg_co2e': 24.5,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Lamb & mutton average — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Segunda carne más emisora tras el vacuno. Incluye emisiones entéricas del animal.'},
 {'category': 'carne_pavo',
  'main_category': 'Alimentación',
  'display_name': 'Carne de pavo',
  'unit': 'kg',
  'factor_kg_co2e': 10.9,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Poultry (turkey) — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Factor superior al pollo por mayor peso y ciclo de cría.'},
 {'category': 'carne_conejo',
  'main_category': 'Alimentación',
  'display_name': 'Carne de conejo',
  'unit': 'kg',
  'factor_kg_co2e': 3.5,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Rabbit — estimación basada en otros animales monogástricos',
  'source_url': None,
  'notes': 'Una de las carnes con menor huella. Buena alternativa de proteína animal.'},
 {'category': 'carne_ternera_lechal',
  'main_category': 'Alimentación',
  'display_name': 'Ternera lechal / veal',
  'unit': 'kg',
  'factor_kg_co2e': 58.0,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Beef (veal) — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Factor muy alto por la ineficiencia del ciclo productivo del veal.'},

 # ─── PESCADOS ESPECÍFICOS ──────────────────────────────────────────────────
 {'category': 'pescado_salmon',
  'main_category': 'Alimentación',
  'display_name': 'Salmón (de piscifactoría)',
  'unit': 'kg',
  'factor_kg_co2e': 6.0,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Farmed salmon — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Factor similar al pollo. El salmón salvaje puede ser algo inferior.'},
 {'category': 'pescado_atun',
  'main_category': 'Alimentación',
  'display_name': 'Atún (fresco o en lata)',
  'unit': 'kg',
  'factor_kg_co2e': 6.1,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Tuna, average — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Incluye la fase de pesca y procesado. No diferencia lata/fresco.'},
 {'category': 'pescado_sardina',
  'main_category': 'Alimentación',
  'display_name': 'Sardinas / boquerones / caballa',
  'unit': 'kg',
  'factor_kg_co2e': 1.2,
  'source_name': 'Ecodes / MITERD',
  'source_year': 2024,
  'source_type': 'scientific_literature',
  'source_detail': 'Peces pelágicos pequeños — Informe Huella Alimentos 2024',
  'source_url': 'https://ecodes.org/images/que-hacemos/MITERD-2023/Informe-Huella-alimentos-2024_def_05062024.pdf',
  'notes': 'Pesca de cerco (menor combustible). Uno de los pescados con menor huella.'},
 {'category': 'pescado_merluza',
  'main_category': 'Alimentación',
  'display_name': 'Merluza / bacalao',
  'unit': 'kg',
  'factor_kg_co2e': 4.5,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Demersal fish — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Peces demersales (fondo). Mayor gasto de combustible por arrastre.'},
 {'category': 'marisco_gambas',
  'main_category': 'Alimentación',
  'display_name': 'Gambas / langostinos (de piscifactoría)',
  'unit': 'kg',
  'factor_kg_co2e': 18.2,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Farmed shrimp — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Factor muy alto principalmente por deforestación de manglares. Uno de los mariscos más emisores.'},

 # ─── LÁCTEOS ESPECÍFICOS ───────────────────────────────────────────────────
 {'category': 'lacteos_yogur',
  'main_category': 'Alimentación',
  'display_name': 'Yogur',
  'unit': 'kg',
  'factor_kg_co2e': 3.0,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Yoghurt — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Factor similar a la leche por contenido mayoritario de ésta.'},
 {'category': 'lacteos_mantequilla',
  'main_category': 'Alimentación',
  'display_name': 'Mantequilla',
  'unit': 'kg',
  'factor_kg_co2e': 11.5,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Butter — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Alto factor por requerir gran cantidad de nata de origen lácteo.'},
 {'category': 'leche_avena',
  'main_category': 'Alimentación',
  'display_name': 'Leche de avena',
  'unit': 'litro',
  'factor_kg_co2e': 0.9,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Oat milk — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'La leche vegetal con menor huella general. ~72% menos emisiones que la leche de vaca.'},
 {'category': 'leche_almendra',
  'main_category': 'Alimentación',
  'display_name': 'Leche de almendra',
  'unit': 'litro',
  'factor_kg_co2e': 0.7,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Almond milk — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Baja huella de carbono pero alto consumo hídrico (problema distinto).'},
 {'category': 'leche_soja',
  'main_category': 'Alimentación',
  'display_name': 'Leche de soja',
  'unit': 'litro',
  'factor_kg_co2e': 0.98,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Soy milk — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Buen perfil proteico. ~70% menos emisiones que leche de vaca.'},

 # ─── VERDURAS ESPECÍFICAS ──────────────────────────────────────────────────
 {'category': 'tomate',
  'main_category': 'Alimentación',
  'display_name': 'Tomate',
  'unit': 'kg',
  'factor_kg_co2e': 1.4,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Tomatoes — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Factor puede ser más alto si se cultiva en invernadero con calefacción.'},
 {'category': 'lechuga_ensalada',
  'main_category': 'Alimentación',
  'display_name': 'Lechuga / ensalada',
  'unit': 'kg',
  'factor_kg_co2e': 0.7,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Brassicas / salad vegetables — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Alimento con huella muy baja. Referencia para comparar con proteína animal.'},
 {'category': 'zanahoria',
  'main_category': 'Alimentación',
  'display_name': 'Zanahoria / raíces',
  'unit': 'kg',
  'factor_kg_co2e': 0.4,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Root vegetables average — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Uno de los alimentos con menor huella por kg.'},
 {'category': 'aguacate',
  'main_category': 'Alimentación',
  'display_name': 'Aguacate',
  'unit': 'kg',
  'factor_kg_co2e': 2.5,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Avocado — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Factor moderado, pero alto consumo hídrico. El transporte por barco añade ~0.21 kg/kg extra si es importado.'},
 {'category': 'cebolla_ajo',
  'main_category': 'Alimentación',
  'display_name': 'Cebolla / ajo / puerro',
  'unit': 'kg',
  'factor_kg_co2e': 0.5,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Onions & alliums — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Alimento muy bajo en emisiones. Pilar de la dieta mediterránea.'},

 # ─── FRUTAS ESPECÍFICAS ────────────────────────────────────────────────────
 {'category': 'naranja_citrico',
  'main_category': 'Alimentación',
  'display_name': 'Naranja / cítricos',
  'unit': 'kg',
  'factor_kg_co2e': 0.4,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Citrus fruit — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Factor muy bajo. España es productor líder mundial, lo que reduce transporte.'},
 {'category': 'platano',
  'main_category': 'Alimentación',
  'display_name': 'Plátano / banana',
  'unit': 'kg',
  'factor_kg_co2e': 0.9,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Bananas — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'A pesar de importarse de lejos, el transporte por barco es eficiente (~8% del total).'},
 {'category': 'manzana_pera',
  'main_category': 'Alimentación',
  'display_name': 'Manzana / pera',
  'unit': 'kg',
  'factor_kg_co2e': 0.4,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Apples — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Factor bajo. Muy habitual en la dieta española.'},
 {'category': 'uvas',
  'main_category': 'Alimentación',
  'display_name': 'Uvas',
  'unit': 'kg',
  'factor_kg_co2e': 0.8,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Grapes — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Factor bajo. Cultivo tradicional en España.'},
 {'category': 'fresas',
  'main_category': 'Alimentación',
  'display_name': 'Fresas / berries',
  'unit': 'kg',
  'factor_kg_co2e': 1.1,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Berries — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Factor puede aumentar si son de invernadero o transporte aéreo.'},

 # ─── FRUTOS SECOS Y SEMILLAS ───────────────────────────────────────────────
 {'category': 'frutos_secos',
  'main_category': 'Alimentación',
  'display_name': 'Frutos secos (nueces, almendras, avellanas)',
  'unit': 'kg',
  'factor_kg_co2e': 0.3,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Nuts — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'De los alimentos con mejor ratio proteína/emisiones. Alternativa muy sostenible.'},
 {'category': 'semillas',
  'main_category': 'Alimentación',
  'display_name': 'Semillas (chía, lino, sésamo)',
  'unit': 'kg',
  'factor_kg_co2e': 1.0,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Seeds average — Science 360(6392)',
  'source_url': None,
  'notes': 'Factor estimado con base en otros cultivos similares de semillas oleaginosas.'},

 # ─── BEBIDAS ──────────────────────────────────────────────────────────────
 {'category': 'te_infusion',
  'main_category': 'Alimentación',
  'display_name': 'Té / infusiones',
  'unit': 'kg',
  'factor_kg_co2e': 6.2,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Tea — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Por kg de hojas secas. Por taza (2g) = ~0.012 kg CO2e. Mucho menos que el café.'},
 {'category': 'bebida_energetica',
  'main_category': 'Alimentación',
  'display_name': 'Bebida energética (lata)',
  'unit': 'unidad',
  'factor_kg_co2e': 0.34,
  'source_name': 'Carbon Trust',
  'source_year': 2021,
  'source_type': 'scientific_literature',
  'source_detail': 'Energy drink 250ml can, lifecycle',
  'source_url': None,
  'notes': 'Incluye producción de lata de aluminio, ingredientes y transporte.'},

 # ─── ALIMENTOS PREPARADOS ─────────────────────────────────────────────────
 {'category': 'pizza',
  'main_category': 'Alimentación',
  'display_name': 'Pizza (congelada o delivery)',
  'unit': 'unidad',
  'factor_kg_co2e': 3.1,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Pizza (cheese-based) estimated from ingredients mix',
  'source_url': None,
  'notes': 'Estimación basada en ingredientes (harina, queso, tomate). Varía según ingredientes.'},
 {'category': 'pasta',
  'main_category': 'Alimentación',
  'display_name': 'Pasta (macarrones, espaguetis)',
  'unit': 'kg',
  'factor_kg_co2e': 1.3,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Wheat-based pasta — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Alimento muy común en la dieta mediterránea con huella moderada-baja.'},
 {'category': 'pan',
  'main_category': 'Alimentación',
  'display_name': 'Pan (barra, integral)',
  'unit': 'kg',
  'factor_kg_co2e': 1.1,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Bread — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Alimento básico de baja huella. Factor levemente superior al trigo por horneado.'},
 {'category': 'aceite_girasol',
  'main_category': 'Alimentación',
  'display_name': 'Aceite de girasol / vegetal',
  'unit': 'litro',
  'factor_kg_co2e': 2.9,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Sunflower oil — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Menor huella que el aceite de oliva por tipo de cultivo y procesado.'},
 {'category': 'azucar',
  'main_category': 'Alimentación',
  'display_name': 'Azúcar (blanca o morena)',
  'unit': 'kg',
  'factor_kg_co2e': 1.8,
  'source_name': 'Poore & Nemecek',
  'source_year': 2018,
  'source_type': 'scientific_literature',
  'source_detail': 'Sugar cane / beet — Science 360(6392)',
  'source_url': 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  'notes': 'Factor moderado. El azúcar de caña puede tener mayor impacto por transporte.'}]

# Alternativas para recomendaciones simples del MVP.
# La recomendación puede comparar el factor de la actividad original con estas opciones.
RECOMMENDATION_ALTERNATIVES = {
 # Transporte
 'coche_gasolina': ['tren', 'tren_alta_velocidad', 'autobus_interurbano', 'metro', 'bicicleta', 'caminar'],
 'coche_diesel': ['tren', 'tren_alta_velocidad', 'autobus_interurbano', 'metro', 'bicicleta', 'caminar'],
 'taxi': ['metro', 'autobus', 'bicicleta', 'caminar'],
 'moto': ['moto_electrica', 'metro', 'autobus', 'bicicleta', 'caminar'],
 'avion_domestico': ['tren_alta_velocidad', 'tren', 'autobus_interurbano'],
 # Energía
 'secadora': ['tender_ropa'],
 'agua_embotellada': ['agua_grifo'],
 # Carnes → alternativas de menor impacto
 'carne_vacuno': ['carne_conejo', 'carne_pollo', 'carne_cerdo', 'legumbres', 'tofu_soja', 'frutos_secos'],
 'carne_ternera_lechal': ['carne_conejo', 'carne_pollo', 'legumbres', 'tofu_soja'],
 'carne_cordero': ['carne_conejo', 'carne_pollo', 'legumbres', 'tofu_soja'],
 'carne_cerdo': ['carne_conejo', 'carne_pollo', 'legumbres', 'tofu_soja'],
 'carne_pavo': ['carne_pollo', 'carne_conejo', 'legumbres', 'frutos_secos'],
 'carne_procesada': ['legumbres', 'tofu_soja', 'huevos', 'frutos_secos'],
 # Marisco de alto impacto
 'marisco_gambas': ['pescado_sardina', 'pescado_merluza', 'legumbres'],
 'marisco': ['pescado_sardina', 'pescado_merluza', 'legumbres'],
 # Lácteos → alternativas vegetales
 'queso': ['lacteos_leche', 'leche_avena', 'huevos', 'tofu_soja'],
 'lacteos_mantequilla': ['aceite_oliva', 'aceite_girasol'],
 'lacteos_leche': ['leche_avena', 'leche_soja', 'leche_almendra'],
 # Bebidas de alto impacto
 'cafe': ['te_infusion'],
 'chocolate': ['frutos_secos', 'fruta', 'fresas'],
 # Alimentos procesados
 'comida_rapida': ['pasta', 'legumbres', 'verduras', 'pan'],
 'pizza': ['pasta', 'legumbres', 'verduras'],
}


def get_factor_by_category(category: str):
    """Devuelve el factor de emisión asociado a una categoría interna."""
    return next((factor for factor in EMISSION_FACTORS if factor["category"] == category), None)


def get_recommendation_alternatives(category: str):
    """Devuelve alternativas más sostenibles para una categoría, si existen."""
    return RECOMMENDATION_ALTERNATIVES.get(category, [])